platform :ios, '9.0'
use_frameworks!
target 'KidZoonaUserApp' do
pod 'Cosmos', '~> 20.0'

  # Pods for Login
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'AppAuth','~> 1.2.0'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

end
